#!/bin/bash - 
#===============================================================================
#
#          FILE: erase_nand.sh
# 
#         USAGE: ./erase_nand.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: tongl (), 
#  ORGANIZATION: 
#       CREATED: 2014年01月16日 12时58分41秒 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

if [ $1 -eq 0 ] || [ $1 -eq 1 ] ; then
    if [ "$2" = "n" ] || [ "$2" = "o"] ; then
        sudo ~/low_work/APPRO/dm36x/sfh_DM36x.exe -nanderase -p /dev/ttyUSB$1
    fi
else
    echo "oh shit you foget it"
fi

